[build]
  publish = "."

# Static file routing - no serverless functions needed
[[redirects]]
  from = "/health"
  to = "/health/index.html"
  status = 200

[[redirects]]
  from = "/api/v1/status"
  to = "/api/v1/status/index.html"
  status = 200