[build]
  publish = "."

# Edge Functions - Complete JurisRank API
[[edge_functions]]
  function = "health"
  path = "/health"

[[edge_functions]]
  function = "status" 
  path = "/api/v1/status"

[[edge_functions]]
  function = "register"
  path = "/api/v1/auth/register"

[[edge_functions]]
  function = "authority"
  path = "/api/v1/jurisprudence/authority"

[[edge_functions]]
  function = "search"
  path = "/api/v1/precedents/search"

[[edge_functions]]
  function = "compare"
  path = "/api/v1/compare/systems"

[[edge_functions]]
  function = "openapi"
  path = "/api/v1/openapi.json"

[[edge_functions]]
  function = "docs"
  path = "/docs"

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"