[build]
  publish = "."

# Edge Functions (JavaScript) - more reliable than Python functions
[[edge_functions]]
  function = "health"
  path = "/health"

[[edge_functions]]
  function = "status" 
  path = "/api/v1/status"

[[edge_functions]]
  function = "register"
  path = "/api/v1/auth/register"

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"